In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/mount/')

Mounted at /content/mount/

#Exploratory Data Analysis

In [ ]:
data = pd.read_csv("/content/mount/MyDrive/datasets/hiring.csv")

print(data.head())
print('\nData Info: \n')
print(data.info())

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

Data Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   experience                  6 non-null      object
 1   test_score(out of 10)       7 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64
 3   salary($)                   8 non-null      int64
dtypes: float64(1), int64(2), object(1)
memory usage: 388.0+ bytes
None

In [ ]:
data.describe()

       test_score(out of 10)  interview_score(out of 10)    salary($)
count               7.000000                    8.000000      8.00000
mean                7.857143                    7.875000  63000.00000
std                 1.345185                    1.642081  11501.55269
min                 6.000000                    6.000000  45000.00000
25%                 7.000000                    6.750000  57500.00000
50%                 8.000000                    7.500000  63500.00000
75%                 8.500000                    9.250000  70500.00000
max                10.000000                   10.000000  80000.00000

In [ ]:
data

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
data.isnull().sum()

experience                    2
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

# Prepocessing

In [ ]:
d = {
    'zero' : 0,
    'one': 1,
    'two': 2,
    'three' : 3,
    'four' : 4,
    'five' : 5,
    'six' : 6,
    'seven' : 7,
    'eight': 8,
    'nine' : 9,
    'ten': 10,
    'eleven': 11
}

data['experience'] = data['experience'].map(d)

data['experience']

0     NaN
1     NaN
2     5.0
3     2.0
4     7.0
5     3.0
6    10.0
7    11.0
Name: experience, dtype: float64

In [ ]:
data['experience'].fillna(0, inplace = True)
data['experience']

0     0.0
1     0.0
2     5.0
3     2.0
4     7.0
5     3.0
6    10.0
7    11.0
Name: experience, dtype: float64

In [ ]:
#test score null value handle
test_score_median = data['test_score(out of 10)'].median()

data['test_score(out of 10)'].fillna(test_score_median, inplace = True)
data['test_score(out of 10)']

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     8.0
7     7.0
Name: test_score(out of 10), dtype: float64

In [ ]:
data.isnull().any()

experience                    False
test_score(out of 10)         False
interview_score(out of 10)    False
salary($)                     False
dtype: bool

#Train the model

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = data[['experience', 'test_score(out of 10)','interview_score(out of 10)']]
y = data['salary($)']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.20, random_state = 42)

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
print('Intercept: ', model.intercept_)
print('Coef1: ', model.coef_[0])
print('Coef2: ', model.coef_[1])
print('Coef3: ', model.coef_[2])

Intercept:  21249.90962766599
Coef1:  2699.1203759489113
Coef2:  2044.824677672008
Coef3:  1635.7392456922514

#evaluation

In [ ]:
from sklearn.metrics import r2_score

y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)

print("r^2 : ", r2)

r^2 :  0.9321989859471912

#prediction

In [ ]:
model.predict([[2,5,6]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([46686.70924208])